# Generated by Django 4.1.2 on 2022-10-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobsModelsBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "jobsmodelsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="jobs.jobsmodelsbase",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("apply_by", models.DateTimeField()),
            ],
            bases=("jobs.jobsmodelsbase",),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "jobsmodelsbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="jobs.jobsmodelsbase",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ap", "Applied"),
                            ("si", "Scheduled Interview"),
                            ("hi", "Hired"),
                            ("dp", "dropped"),
                        ],
                        default="ap",
                        max_length=10,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
            ],
            bases=("jobs.jobsmodelsbase",),
        ),
    ]
