# Generated by Django 4.1.2 on 2022-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_positions_job_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="contract_type",
            field=models.CharField(
                default="temporary",
                help_text="e.g temporary, full time, ...",
                max_length=35,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                blank=True,
                help_text="e.g internship, entry level, ...",
                max_length=35,
                null=True,
            ),
        ),
    ]
