# Generated by Django 4.1.2 on 2022-10-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_is_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(default="hjdhfjnsdfiosdjkfnu"),
            preserve_default=False,
        ),
    ]
