# Generated by Django 4.1.2 on 2022-10-26 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "accountbasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounts.accountbasemodel",
                    ),
                ),
                ("confirmed_email", models.BooleanField(default=False)),
                ("phone_number", models.CharField(max_length=100)),
                ("alternative_email", models.EmailField(max_length=254)),
                (
                    "registered_id",
                    models.CharField(max_length=15, verbose_name="ID/Alien Number"),
                ),
                (
                    "education",
                    models.TextField(
                        choices=[
                            (1, "Certificate"),
                            (2, "Diploma"),
                            (3, "Degree"),
                            (4, "Masters"),
                            (5, "Masters & MBA"),
                        ],
                        default=1,
                        max_length=20,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        help_text="put an acurate represantation of your experience",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateTimeField()),
                ("town", models.CharField(max_length=65)),
                ("nationality", models.CharField(max_length=35)),
                ("current_location", models.CharField(max_length=155)),
                ("prefered_work_location", models.CharField(max_length=155)),
                (
                    "languages",
                    models.CharField(help_text="comma separated", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("accounts.accountbasemodel",),
        ),
    ]
