# Generated by Django 4.1.2 on 2022-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="current_location",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="languages",
            field=models.CharField(
                blank=True, help_text="comma separated", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="prefered_work_location",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="town",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
