# Generated by Django 4.1.2 on 2022-10-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_current_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(
                choices=[
                    ("cert", "Certificate"),
                    ("dip", "Diploma"),
                    ("deg", "Degree"),
                    ("mas", "Masters"),
                ],
                default="cert",
                max_length=20,
            ),
        ),
    ]
