# Generated by Django 4.1.2 on 2022-10-28 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resume.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeBaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Referee",
            fields=[
                (
                    "resumebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="resume.resumebasemodel",
                    ),
                ),
                ("referee_name", models.CharField(max_length=155)),
                ("organization_name", models.CharField(max_length=155)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("resume.resumebasemodel",),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "resumebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="resume.resumebasemodel",
                    ),
                ),
                ("from_date", models.DateField(verbose_name="From")),
                ("to_date", models.DateField(verbose_name="To")),
                ("organization_name", models.CharField(max_length=100)),
                ("position", models.CharField(help_text="Job title", max_length=40)),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Salary (Ksh)"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Brief description of your roles"),
                ),
                ("why_left", models.TextField(verbose_name="Reasons for leaving")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("resume.resumebasemodel",),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "resumebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="resume.resumebasemodel",
                    ),
                ),
                ("from_date", models.DateField(verbose_name="From")),
                ("to_date", models.DateField(verbose_name="To")),
                ("institution_name", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=155)),
                (
                    "enrolled",
                    models.BooleanField(
                        help_text="Are you still attending for classes ?"
                    ),
                ),
                ("grade", models.CharField(max_length=35)),
                ("your_achievements", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("resume.resumebasemodel",),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "resumebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="resume.resumebasemodel",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("cv", "Curriculum Vitae"),
                            ("Academic", "Certificates"),
                        ],
                        default="resume",
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "doc_name",
                    models.CharField(max_length=40, verbose_name="Document Name"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=resume.models.document_upload_path,
                        verbose_name="Document(PDF)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("resume.resumebasemodel",),
        ),
    ]
