# Generated by Django 4.1.2 on 2022-10-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="in_role",
            field=models.BooleanField(
                default=False, verbose_name="Are you still working here ?"
            ),
        ),
        migrations.AddField(
            model_name="referee",
            name="call",
            field=models.BooleanField(
                default=True, verbose_name="Available for call ?"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="enrolled",
            field=models.BooleanField(
                default=False, help_text="Are you still attending for classes ?"
            ),
        ),
    ]
