# Generated by Django 4.1.2 on 2022-10-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_experience_in_role_referee_call_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-to_date"]},
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-to_date"]},
        ),
    ]
